---
title: "asdf"
author: '480344766'
date: "05/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(plotly)
```


```{r}

data = t(read.table("./prices250.txt")) %>% as.data.frame()
colnames(data) = paste0("t", 1:ncol(data))
data = data %>% mutate(instrument = paste0("instrument", 1:nrow(data)))

data_long = pivot_longer(data, cols = "t1":"t250", names_to = "time", values_to = "price")
```

```{r}

p1 = ggplot(data_long) +
  aes(x = time, y = price, group = instrument, colour = instrument) +
  geom_line() +
  labs(x = "Time", y = "Price") +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

plotly::ggplotly(p1)

# ggsave("figures/summary_plot.jpg", p1, height = 7, width = 15)
```

```{r instrument 27}

p2 = ggplot(data_long %>% filter(instrument == "instrument27")) +
  aes(x = time, y = price, group = instrument, colour = instrument) +
  geom_line() +
  labs(x = "Time", y = "Price") +
  ylim(10, 20) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

p2

# ggsave("figures/instrument27.jpg", p2, height = 7, width = 15)
```


